name: Unzip and commit

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Unzip file
      # For Ubuntu or macOS
      run: unzip 1.zip -d .
      # For Windows, you can use the following command:
      # run: Expand-Archive -Path 1.zip -DestinationPath .

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Unzip and commit files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
